WCIG6/Controllers/Vendors/VendorsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WCIG6.Business.VendorVerification;
using WCIG6.Models;
using WCIG6.ViewModels.Cabinet;

namespace WCIG6.Controllers
{
    public class VendorsController : Controller
    {
        private static readonly bool USE_VERIFICATION_CODES = false;

        private readonly VendorVerifier vendorVerifier;
        private readonly UserManager<Vendor> userManager;
        private readonly SignInManager<Vendor> signInManager;
        private readonly ILogger<VendorsController> logger;

        public VendorsController(
            VendorVerifier vendorVerifier,
            UserManager<Vendor> userManager,
            SignInManager<Vendor> signInManager,
            ILogger<VendorsController> logger
        ) {
            this.vendorVerifier = vendorVerifier;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.logger = logger;
        }

        public IActionResult Enter()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Cabinet");
            }

            ViewBag.IsLogin = false;

            return View(new EnterViewModel
            {
                Login = new LoginViewModel(),
                Register = new RegisterViewModel(),
            });
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            // Makig sure that user signing in is verified
            var user = await userManager.FindByEmailAsync(model.Email);

            if(user == null || !user.IsVerified)
            {
                ModelState.AddModelError(string.Empty, "Invalid email or password");
            }
            else
            {
                // Can only sign in with username -> Having to find a user with a matching email first
                var result = await signInManager.PasswordSignInAsync(
                    model.Email,
                    model.Password,
                    true,
                    false
                );

                if (!result.Succeeded)
                {
                    ModelState.AddModelError(string.Empty, "Invalid email or password");
                }
            }

            if (!ModelState.IsValid)
            {
                ViewBag.IsLogin = true;

                return View("Enter", new EnterViewModel
                {
                    Login = model,
                    Register = new RegisterViewModel(),
                });
            }

            return RedirectToAction("Index", "Cabinet");
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            var vendor = new Vendor()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                PhoneNumber = model.Phone,
                UserName = model.Email,
                Email = model.Email,
                Website = model.Website,
                IsVerified = !USE_VERIFICATION_CODES, // If no codse are used, vendor would automatically be verified
            };

            var verificationResult = vendorVerifier.verify(vendor);

            if (!verificationResult.IsSuccessful)
            {
                foreach (var error in verificationResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                }
            }

            if (ModelState.IsValid)
            {
                var result = await userManager.CreateAsync(vendor, model.Password);

                if (!result.Succeeded)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
                else
                {
                    await signInManager.SignInAsync(vendor, false);
                }
            }

            if (!ModelState.IsValid)
            {
                ViewBag.IsLogin = false;

                return View("Enter", new EnterViewModel
                {
                    Register = model,
                    Login = new LoginViewModel(),
                });
            }

            if(!USE_VERIFICATION_CODES)
            {
                return RedirectToAction("Index", "Cabinet");
            }
            else
            {
                vendorVerifier.sendCodes(vendor);

                return View("Verify");
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Exit()
        {
            await signInManager.SignOutAsync();

            return RedirectToAction("Enter");
        }
    }
}

WCIG6/Views/Vendors/Enter.cshtml
@model WCIG6.ViewModels.Cabinet.EnterViewModel
@{
    ViewData["Title"] = "Enter Vendor's Cabinet";
}

<div class="text-center">
    <h1 class="display-4 mb-4">Enter Vendor's Cabinet</h1>

    <div class="row">
        <div class="col-sm">
            <h3 class="display-5">Existing Vendor</h3>
            <form asp-controller="Vendors" asp-action="Login" method="post">
                <div class="form-group">
                    <input name="Email" value="@Model.Login.Email" type="email" class="form-control" placeholder="Email Address">
                </div>
                <div class="form-group">
                    <input name="Password" value="@Model.Login.Password" type="password" class="form-control" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Log In</button>
                @if (ViewBag.IsLogin)
                {
                    <div asp-validation-summary="All" class="text-danger text-justify mt-3"></div>
                }
            </form>
        </div>
        <div class="col-sm">
            <h3 class="display-5">New Vendor</h3>
            <form asp-controller="Vendors" asp-action="Register" method="post">
                <div class="form-group">
                    <input name="FirstName" value="@Model.Register.FirstName" type="text" class="form-control" placeholder="First Name">
                </div>
                <div class="form-group mb-5">
                    <input name="LastName" value="@Model.Register.LastName" type="text" class="form-control" placeholder="Last Name">
                </div>
                <div class="form-group">
                    <input name="Password" value="@Model.Register.Password" type="password" class="form-control" placeholder="Password">
                </div>
                <div class="form-group mb-5">
                    <input name="RepeatPassword" value="@Model.Register.RepeatPassword" type="password" class="form-control" placeholder="Repeat Password">
                </div>
                <div class="form-group">
                    <input name="Phone" value="@Model.Register.Phone" type="tel" class="form-control" placeholder="Phone Number">
                </div>
                <div class="form-group">
                    <input name="Email" value="@Model.Register.Email" type="email" class="form-control" placeholder="Email Address">
                </div>
                <div class="form-group">
                    <input name="Website" value="@Model.Register.Website" type="url" class="form-control" placeholder="Link to website (Optional)">
                </div>
                <button type="submit" class="btn btn-primary">Register</button>
                @if (!ViewBag.IsLogin)
                {
                    <div asp-validation-summary="All" class="text-danger text-justify mt-3"></div>
                }
            </form>
        </div>
    </div>
</div>

WCIG6/Views/Vendors/Verify.cshtml
<p>Please verify your contact information.</p>