WCIG6/Controllers/Plants/PlantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WCIG6.Models;
using WCIG6.ViewModels;

namespace WCIG6.Controllers
{
    public class PlantsController : Controller
    {
        private Database _db;

        public PlantsController( Database db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetPlantData(HomeViewModel viewModel)

        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            viewModel.Plants = _db.Plant.Where(x => x.HardinessZone <= viewModel.HardinessZone)
                .ToList();
            List<Area> AreaList = _db.Area.ToList();
            viewModel.AreaList = AreaList;
            return View( "Index", viewModel);
        }

        [HttpPost]
        public IActionResult GetPlantDataByCity(HomeViewModel viewModel)

        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            int cityZone = _db.Area.FirstOrDefault(x => x.Name.ToLower().Equals(viewModel.CityName.ToLower())).HardinessZone;
            viewModel.HardinessZone = cityZone;
            viewModel.Plants = _db.Plant.Where(x => x.HardinessZone <= viewModel.HardinessZone)
                .ToList();
            List<Area> AreaList = _db.Area.ToList();
            viewModel.AreaList = AreaList;
            return View("Index", viewModel);
        }


        public IActionResult PlantDetails()
        {
            return View();
        }

        public IActionResult SearchSeeds()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SearchSeeds(SeedSearchViewModel model)
        {
            return View();
        }
    }
}

WCIG6/Controllers/Research/ResearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using WCIG6.Models;
using WCIG6.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace WCIG6.Controllers
{
    
    public class ResearchController : Controller
    {
        private Database _db;

        public ResearchController(Database database)
        {
            _db = database;
        }

        public IActionResult Index(ResearchViewModel viewModel)
        {
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult GetClimateData(ResearchViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            var climateReports = _db.ClimateReport.Where(x => viewModel.StartYear <= x.Year && x.Year <= viewModel.EndYear && x.Area.Name == viewModel.Location)
                .ToList();

            var options = new JsonSerializerOptions
            {
                WriteIndented = true,
                IgnoreNullValues = true
            };
            viewModel.DataJson = JsonSerializer.Serialize(climateReports,options);

            return View("Index", viewModel);
        }

        [HttpPost]
        public IActionResult GetPlantData(ResearchViewModel viewModel)
        {
            //TODO: Set the viewModel.DataJson to some plant data
            return View("Index", viewModel);
        }
    }
}

WCIG6/Views/Shared/Index.cshtml
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 mb-4">Welcome to WhatCanIGrow!</h1>


    @*<form class="form-group" method="post">
        <input class="form-control" id="location" placeholder="Adderss, Postal Code, etc...">
        <a asp-action="FindPlants" type="submit" class="btn btn-primary my-3">Find Plants</a>
    </form>*@
    <div>
        <p>
            Note for professor* Since for now the plant data is seeded into the db we have a limited number of plants, searching by major city works 
            but if its not obvious we have added 2 fake cities with min and max zones called "Low" and "High" to confirm functinoality for you.
        </p>
    </div>

    <div class="row">
        <div class="col-4">
            <div class="list-group" id="list-tab" role="tablist">

                <form asp-controller="Plants" asp-action="GetPlantData" method="post">

                    <input asp-for="HardinessZone" id="location" class="form-control mb-3" type="text" placeholder="Enter Zone" />


                    <button class="form-control mb-3" type="submit">Find plants by hardiness Zone</button>

                </form>

                <form asp-controller="Plants" asp-action="GetPlantDataByCity" method="post">

                    <input asp-for="CityName" id="location" class="form-control mb-3" type="text" placeholder="Enter City" />


                    <button class="form-control mb-3" type="submit">Find plants and zone by City Name </button>

                </form>

                @*@foreach (var item in Model.AreaList)
        {
            @if (item.AreaId.Equals(Model.AreaList.First().AreaId))
            {
                <form asp-controller="Plants" asp-action="GetPlantData" method="post">

                    <input asp-for="HardinessZone" id="location" class="form-control mb-3" type="text" placeholder="Location" />


                    <button class="form-control mb-3" type="submit">Find plants by hardiness Zone</button>

                </form>
            }
            else
            {
                <a class="list-group-item list-group-item-action"
                   id="@item.AreaId" data-toggle="list"
                   role="tab" aria-controls="@item.Name"
                   href="#@item.Name">@item.Name</a>
            }
        }*@
            </div>
        </div>
        <div class="col-8">
            @*<div class="tab-content" id="nav-tabContent">

                @foreach (var item in Model.AreaList)
                {
                    @if (item.AreaId.Equals(Model.AreaList.First().AreaId))
                    {
                        <div class="tab-pane fade show active" id="@item.Name" role="tabpanel" aria-labelledby="@item.AreaId">Toronto</div>

                    }
                    else
                    {
                        <div class="tab-pane fade" id="@item.Name" role="tabpanel" aria-labelledby="list-Montreal-list">@item.Name</div>
                    }

                }*@
                @*<div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">1234</div>
            <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">434343</div>
            <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">555</div>
            <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">342342</div>*@
            @*</div>*@

            <div class="col-sm text-left">
                <div class="bg-dark rounded shadow-sm p-3">
                    <pre class="text-white">
                    @if (Model.Plants != null) {
                         @foreach (var plant in Model.Plants)
                        {
                            @if (plant.PlantId.Equals(Model.Plants.First().PlantId))
                            {
                            <div class="text-white" id="@plant.Name" role="tabpanel" aria-labelledby="@plant.PlantId">@plant.Name</div>

                            }
                            else
                            {
                            <div class="text-white" id="@plant.Name" role="tabpanel" aria-labelledby="list-Montreal-list">@plant.Name</div>
                            }

                        }
                    }
                </pre>
                </div>
            </div>

        </div>
    </div>

</div>

<script>


        $("#slider-range-max").slider({
                        range: "max",
            min: 1,
            max: 13,
            value: 2,
            slide: function (event, ui) {
                $("#zonedisplay").val(ui.value);
                    }
                    });
    $("#zonedisplay").val($("#slider-range-max").slider("value"));

</script>

WCIG6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WhatCanIGrow</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">WhatCanIGrow</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="nav-link text-dark" asp-controller="Plants" asp-action="SearchSeeds" title="Seeds Search">
                    Seeds Search
                </a>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <a class="nav-link text-dark" asp-controller="Research" asp-action="Index" title="Researcher">
                        Research
                    </a>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WhatCanIGrow
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>