WCIG6/Controllers/Cabinet/CabinetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WCIG6.Business.SeedRegistration;
using WCIG6.Models;
using WCIG6.ViewModels.Cabinet;

namespace WCIG6.Controllers
{
    public class CabinetController : Controller
    {
        private readonly Database database;
        private readonly SeedBuilderFactory seedBuilderFactory;
        private readonly UserManager<Vendor> userManager;
        private readonly ILogger<CabinetController> logger;

        private Task<Vendor> currentVendor()
        {
            return userManager.GetUserAsync(HttpContext.User);
        }

        private async Task<Seed> findSeed(int seedId, Vendor vendor)
        {
            var seed = await database.Seed
                .Include(seed => seed.Plant)
                .Include(seed => seed.Vendor)
                .SingleOrDefaultAsync(seed => seed.SeedId == seedId && seed.Vendor.Id == vendor.Id);

            return seed;
        }

        private async Task<bool> checkSeed(int seedId, Vendor vendor)
        {
            var count = await database.Seed
                .Include(seed => seed.Vendor)
                .CountAsync(seed => seed.SeedId == seedId && seed.Vendor.Id == vendor.Id);

            return count > 0;
        }

        private async Task changeSeedVisibility(int seedId, bool isVisible)
        {
            var vendor = await currentVendor();
            var seed = await findSeed(seedId, vendor);

            if (seed != null)
            {
                seed.IsVisible = isVisible;

                database.Seed.Update(seed);

                await database.SaveChangesAsync();
            }
        }

        private SeedBuilder buildSeedFrom(SeedViewModel viewModel, Vendor vendor)
        {
            var builder = seedBuilderFactory.forPlant(viewModel.PlantId)
                .withName(viewModel.SeedName)
                .withPrice(viewModel.Price ?? 0)
                .withDescription(viewModel.Description)
                .withVisibility(viewModel.IsPublished)
                .withVendor(vendor);

            if(viewModel.HardinessZone >= 0)
            {
                builder.withHardinessZone(viewModel.HardinessZone);
            }

            return builder;
        }

        private List<Plant> loadPlants()
        {
            return database.Plant.ToList();
        }

        private IActionResult seedFormView(bool isNew, int? seedId, SeedViewModel model)
        {
            ViewBag.IsNew = isNew;

            if(seedId != null)
            {
                ViewBag.SeedId = seedId;
            }

            ViewBag.Plants = loadPlants();

            return View("SeedForm", model);
        }

        public CabinetController(
            Database database,
            SeedBuilderFactory seedBuilderFactory,
            UserManager<Vendor> userManager,
            ILogger<CabinetController> logger
        ) {
            this.database = database;
            this.seedBuilderFactory = seedBuilderFactory;
            this.userManager = userManager;
            this.logger = logger;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var vendor = await currentVendor();

            var seeds = database.Seed
                .Include(seed => seed.Plant)
                .Where(seed => seed.Vendor.Id == vendor.Id)
                .ToList();

            return View(seeds);
        }

        [Authorize]
        public async Task<IActionResult> PublishSeed(int seedId)
        {
            await changeSeedVisibility(seedId, true);

            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> UnpublishSeed(int seedId)
        {
            await changeSeedVisibility(seedId, false);

            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> DeleteSeed(int seedId)
        {
            var vendor = await currentVendor();
            var seed = await findSeed(seedId, vendor);

            if(seed != null)
            {
                database.Seed.Remove(seed);

                await database.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public IActionResult AddSeed()
        {
            return seedFormView(true, null, new SeedViewModel());
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddSeed(SeedViewModel model)
        {
            var vendor = await currentVendor();

            var result = buildSeedFrom(model, vendor).build();

            if(!result.IsSuccessful)
            {
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                }
            }

            if(!ModelState.IsValid)
            {
                return seedFormView(true, null, model);
            }

            database.Seed.Add(result.Seed);

            database.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditSeed(int id)
        {
            var vendor = await currentVendor();
            var seed = await findSeed(id, vendor);

            if(seed == null)
            {
                return RedirectToAction("Index");
            }

            return seedFormView(false, id, new SeedViewModel(seed));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditSeed(int id, SeedViewModel model)
        {
            var vendor = await currentVendor();
            var check = await checkSeed(id, vendor);

            if (!check)
            {
                return RedirectToAction("Index");
            }

            var result = buildSeedFrom(model, vendor).build(id);

            if (!result.IsSuccessful)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                }
            }

            if (!ModelState.IsValid)
            {
                return seedFormView(false, id, model);
            }

            database.Seed.Update(result.Seed);

            database.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

WCIG6/Views/Cabinet/Index.cshtml
@model ICollection<Seed>
@{
    ViewData["Title"] = "My Cabinet";
}

<div class="text-center">
    <h1 class="display-4 mb-5">My Seeds</h1>

    <div class="d-flex justify-content-end">
        <a asp-action="AddSeed" class="btn btn-link">Add a new kind of seeds</a>
    </div>
    @if (Model.Count > 0)
    {
        <div class="list-group seeds-list">
            @foreach (var seed in Model)
            {
                <div class="list-group-item list-group-item-action d-flex flex-row align-items-center justify-content-between">
                    <div class="d-flex flex-column justify-content-between align-items-start">
                        <div class="d-flex flex-column align-items-start">
                            <h5 class="mb-1">@seed.Name</h5>
                            <p>@seed.Plant.Name</p>
                        </div>
                        <p class="mb-1"><b>Price per KG: @seed.FormattedPricePerKG</b></p>
                    </div>
                    <div>
                        @if (seed.IsVisible)
                        {
                            <button class="btn btn-secondary" data-unpublish data-seed="@seed.SeedId">Unpublish</button>
                        }
                        else
                        {
                            <button class="btn btn-primary" data-publish data-seed="@seed.SeedId">Publish</button>
                        }
                        <button class="btn btn-danger" data-delete="@(seed.IsVisible ? "0" : "1")" data-seed="@seed.SeedId">Delete</button>
                        <a asp-action="EditSeed" asp-route-id="@seed.SeedId" class="btn btn-warning">Edit</a>
                    </div>
                </div>
            }
        </div>
    }
    else
    {
        <h5 class="empty-label">You currently have no seeds registered</h5>
    }
</div>

<div id="deleteDialog" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Are you sure?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Would you like to simply unpublish the seeds instead?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal" id="unpublishButton">Unpublish</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal" id="deleteButton">Delete</button>
            </div>
        </div>
    </div>
</div>

@* Hidden forms for performing various actions *@

<form asp-controller="Cabinet" asp-action="DeleteSeed" method="post" id="deleteForm">
    <input type="hidden" name="seedId" />
</form>

<form asp-controller="Cabinet" asp-action="UnpublishSeed" method="post" id="unpublishForm">
    <input type="hidden" name="seedId" />
</form>

<form asp-controller="Cabinet" asp-action="PublishSeed" method="post" id="publishForm">
    <input type="hidden" name="seedId" />
</form>

@section Scripts {
    <script src="~/js/seeds-list.js" asp-append-version="true"></script>
}

WCIG6/Views/Cabinet/SeedForm.cshtml
@model WCIG6.ViewModels.Cabinet.SeedViewModel
@{
    ViewData["Title"] = ViewBag.IsNew ? "Create a new kind of seeds" : "Edit the selected kind of seeds";
}

<div class="text-center">
    <h1 class="display-4 mb-4">Enter seeds details</h1>
</div>

<form method="post">
    <div class="form-group">
        <input asp-for="SeedName" class="form-control" placeholder="Name of the seeds">
    </div>
    <div class="form-group">
        <select asp-for="PlantId" class="form-control">
            <option disabled selected value="0">--Select Plant--</option>
            @foreach (Plant plant in ViewBag.Plants)
            {
                <option value="@plant.PlantId">@plant.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">$/KG</span>
            </div>
            <input asp-for="Price" type="number" class="form-control" placeholder="Price of seeds per KG" step="0.01" />
        </div>
    </div>
    <div class="form-group">
        <select asp-for="HardinessZone" class="form-control">
            @for (int i = -1; i <= 13; i++)
            {
                <option value="@i">@(i == -1 ? "--Hardiness Zone--" : $"Zone {i}")</option>
            }
        </select>
        <small class="form-text text-muted">Plant's default hardiness-zones are going to be used otherwise.</small>
    </div>
    <div class="form-group">
        <textarea asp-for="Description" class="form-control" placeholder="Description"></textarea>
    </div>
    <input type="hidden" asp-for="IsPublished" id="isPublishedInput" />
    <div class="d-flex justify-content-end">
        <button type="button" class="btn btn-primary" id="registerButton">@(ViewBag.IsNew ? "Register" : "Save")</button>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
</form>

<div id="publishDialog" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Notice</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Would you like to have the seed published right away?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal" id="publishButton">Yes</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal" id="saveButton">No</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        var isNew = @(ViewBag.IsNew ? "true" : "false");
    </script>
    <script src="~/js/seeds-form.js" asp-append-version="true"></script>
}